<?php
/**
 * @var $block \Brainspin\CheckoutProcess\Block\Adminhtml\Order\View\View
 */
?>
<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?php echo $block->myFunction()?></span>
    </div>

    <div class="admin__page-section-content">
        <h3>This is where I'm going to group the products into shipments. </h3></br>
    </div>
</section>